aws:
  access-key: ""
  secret-key: ""
  dynamodb:
    #endpoint: "http://localhost:8000"
   
cloud:
  aws:
    stack:
      auto: false
    region:
      static: us-east-1


spring:
  data:
    dynamodb:
      entity2ddl:
        auto: validate